//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.07.30 at 05:45:01 AM IST 
//


package com.wu.solargalaxyservice.galaxy;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MobileFeature complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MobileFeature">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="featureId" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="ram" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="rom" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="extendableRom" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="displaySize" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="frontEndCamera" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="backEndCamera" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="batteryPower" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="processor" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MobileFeature", propOrder = {
    "featureId",
    "ram",
    "rom",
    "extendableRom",
    "displaySize",
    "frontEndCamera",
    "backEndCamera",
    "batteryPower",
    "processor"
})
public class MobileFeature {

    protected long featureId;
    protected long ram;
    protected long rom;
    protected long extendableRom;
    protected double displaySize;
    protected int frontEndCamera;
    protected int backEndCamera;
    protected long batteryPower;
    @XmlElement(required = true)
    protected String processor;

    /**
     * Gets the value of the featureId property.
     * 
     */
    public long getFeatureId() {
        return featureId;
    }

    /**
     * Sets the value of the featureId property.
     * 
     */
    public void setFeatureId(long value) {
        this.featureId = value;
    }

    /**
     * Gets the value of the ram property.
     * 
     */
    public long getRam() {
        return ram;
    }

    /**
     * Sets the value of the ram property.
     * 
     */
    public void setRam(long value) {
        this.ram = value;
    }

    /**
     * Gets the value of the rom property.
     * 
     */
    public long getRom() {
        return rom;
    }

    /**
     * Sets the value of the rom property.
     * 
     */
    public void setRom(long value) {
        this.rom = value;
    }

    /**
     * Gets the value of the extendableRom property.
     * 
     */
    public long getExtendableRom() {
        return extendableRom;
    }

    /**
     * Sets the value of the extendableRom property.
     * 
     */
    public void setExtendableRom(long value) {
        this.extendableRom = value;
    }

    /**
     * Gets the value of the displaySize property.
     * 
     */
    public double getDisplaySize() {
        return displaySize;
    }

    /**
     * Sets the value of the displaySize property.
     * 
     */
    public void setDisplaySize(double value) {
        this.displaySize = value;
    }

    /**
     * Gets the value of the frontEndCamera property.
     * 
     */
    public int getFrontEndCamera() {
        return frontEndCamera;
    }

    /**
     * Sets the value of the frontEndCamera property.
     * 
     */
    public void setFrontEndCamera(int value) {
        this.frontEndCamera = value;
    }

    /**
     * Gets the value of the backEndCamera property.
     * 
     */
    public int getBackEndCamera() {
        return backEndCamera;
    }

    /**
     * Sets the value of the backEndCamera property.
     * 
     */
    public void setBackEndCamera(int value) {
        this.backEndCamera = value;
    }

    /**
     * Gets the value of the batteryPower property.
     * 
     */
    public long getBatteryPower() {
        return batteryPower;
    }

    /**
     * Sets the value of the batteryPower property.
     * 
     */
    public void setBatteryPower(long value) {
        this.batteryPower = value;
    }

    /**
     * Gets the value of the processor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProcessor() {
        return processor;
    }

    /**
     * Sets the value of the processor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProcessor(String value) {
        this.processor = value;
    }

}
