//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.07.30 at 05:45:01 AM IST 
//


package com.wu.solargalaxyservice.galaxy;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.wu.solargalaxyservice.galaxy package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _GetGreetResponse_QNAME = new QName("http://www.wu.com/solargalaxyservice/galaxy", "GetGreetResponse");
    private final static QName _GetMobileRequest_QNAME = new QName("http://www.wu.com/solargalaxyservice/galaxy", "GetMobileRequest");
    private final static QName _GetMobileByIdRequest_QNAME = new QName("http://www.wu.com/solargalaxyservice/galaxy", "GetMobileByIdRequest");
    private final static QName _GetMobileByNameOrWithoutNameRequest_QNAME = new QName("http://www.wu.com/solargalaxyservice/galaxy", "GetMobileByNameOrWithoutNameRequest");
    private final static QName _GetGreetRequest_QNAME = new QName("http://www.wu.com/solargalaxyservice/galaxy", "GetGreetRequest");
    private final static QName _RemoveMobileByIdResponse_QNAME = new QName("http://www.wu.com/solargalaxyservice/galaxy", "RemoveMobileByIdResponse");
    private final static QName _AddMobileResponse_QNAME = new QName("http://www.wu.com/solargalaxyservice/galaxy", "AddMobileResponse");
    private final static QName _RemoveMobileByIdRequest_QNAME = new QName("http://www.wu.com/solargalaxyservice/galaxy", "RemoveMobileByIdRequest");
    private final static QName _UpdateMobileByIdResponse_QNAME = new QName("http://www.wu.com/solargalaxyservice/galaxy", "UpdateMobileByIdResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.wu.solargalaxyservice.galaxy
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetMobileByNameOrWithoutNameResponse }
     * 
     */
    public GetMobileByNameOrWithoutNameResponse createGetMobileByNameOrWithoutNameResponse() {
        return new GetMobileByNameOrWithoutNameResponse();
    }

    /**
     * Create an instance of {@link MobileList }
     * 
     */
    public MobileList createMobileList() {
        return new MobileList();
    }

    /**
     * Create an instance of {@link MobileFeature }
     * 
     */
    public MobileFeature createMobileFeature() {
        return new MobileFeature();
    }

    /**
     * Create an instance of {@link AddMobileRequest }
     * 
     */
    public AddMobileRequest createAddMobileRequest() {
        return new AddMobileRequest();
    }

    /**
     * Create an instance of {@link GetMobileByIdResponse }
     * 
     */
    public GetMobileByIdResponse createGetMobileByIdResponse() {
        return new GetMobileByIdResponse();
    }

    /**
     * Create an instance of {@link UpdateMobileByIdRequest }
     * 
     */
    public UpdateMobileByIdRequest createUpdateMobileByIdRequest() {
        return new UpdateMobileByIdRequest();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.wu.com/solargalaxyservice/galaxy", name = "GetGreetResponse")
    public JAXBElement<String> createGetGreetResponse(String value) {
        return new JAXBElement<String>(_GetGreetResponse_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.wu.com/solargalaxyservice/galaxy", name = "GetMobileRequest")
    public JAXBElement<String> createGetMobileRequest(String value) {
        return new JAXBElement<String>(_GetMobileRequest_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.wu.com/solargalaxyservice/galaxy", name = "GetMobileByIdRequest")
    public JAXBElement<Long> createGetMobileByIdRequest(Long value) {
        return new JAXBElement<Long>(_GetMobileByIdRequest_QNAME, Long.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.wu.com/solargalaxyservice/galaxy", name = "GetMobileByNameOrWithoutNameRequest")
    public JAXBElement<String> createGetMobileByNameOrWithoutNameRequest(String value) {
        return new JAXBElement<String>(_GetMobileByNameOrWithoutNameRequest_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.wu.com/solargalaxyservice/galaxy", name = "GetGreetRequest")
    public JAXBElement<String> createGetGreetRequest(String value) {
        return new JAXBElement<String>(_GetGreetRequest_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.wu.com/solargalaxyservice/galaxy", name = "RemoveMobileByIdResponse")
    public JAXBElement<Boolean> createRemoveMobileByIdResponse(Boolean value) {
        return new JAXBElement<Boolean>(_RemoveMobileByIdResponse_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.wu.com/solargalaxyservice/galaxy", name = "AddMobileResponse")
    public JAXBElement<Boolean> createAddMobileResponse(Boolean value) {
        return new JAXBElement<Boolean>(_AddMobileResponse_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.wu.com/solargalaxyservice/galaxy", name = "RemoveMobileByIdRequest")
    public JAXBElement<Long> createRemoveMobileByIdRequest(Long value) {
        return new JAXBElement<Long>(_RemoveMobileByIdRequest_QNAME, Long.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.wu.com/solargalaxyservice/galaxy", name = "UpdateMobileByIdResponse")
    public JAXBElement<Boolean> createUpdateMobileByIdResponse(Boolean value) {
        return new JAXBElement<Boolean>(_UpdateMobileByIdResponse_QNAME, Boolean.class, null, value);
    }

}
